### ISSUE TITLE
The main spirit of Kmol editor

### ISSUE THREAD

**Issue by KmolYuan** [mdecourse/kll3pp#4]
關於 [Kmol editor](https://github.com/KmolYuan/kmol-editor) 的一些想法。

*註：部分內容尚未實現。*

+ 簡單、快速版本的 Leo editor。考慮模組：PyQt 周邊。

+ 作為支援下列語言的 IDE：

    + Markdown：Pelican 網誌系統與 Pandoc 論文系統。
    + HTML：reveal.js 簡報框架為主，由於 HTML 結構不易拿捏，後續支援可能待需求再跟進。
    + Python：透過 `eval` 函式實現直譯功能與腳本化，給學員進行互動，進而改進 Kmol editor 本身。
    + 基本上支援所有 QScintilla 的語法亮顯，能編輯其他文本檔案，並提供文本內的自動完成。

+ 功能實現：

    + 特別強化上述三種語言的支援。
    + 學員自行開發應對其他需求。討論：<https://github.com/KmolYuan/kmol-editor/issues>

+ 改善 Leo editor 儲存方式：

    + 問題：當使用 `@clean` 節點時，Leo editor 會將內容分割儲存。這樣會導致檔案龐大、存讀檔速度慢、無法以其他編輯器開啟，因為定點會跑掉。

    + 方法 - 自動解析：固定的解析方式，只有開啟檔案時才會啟動。
        + Markdown 透過 header 階層解析。
        + HTML 透過特定 tag 節點解析（例如 `<style>` 和 `<section>`），其他部分歸類在一起。
        + Python 與其他文件參照 `@edit` 節點的方式不解析直接讀取，否則有上下文無法串連的問題。

+ 大綱識別：

    + 沿用 Leo 的 `@others`。
    + `@button` 的部分以勾選設定呈現，另外有隨時可用的 run script 鈕。
    + `@path` 改成節點的 path 屬性。
    + 支援 clone node。
    + 因存檔問題取消 `@edit`、`@clean`，其他標籤暫不考慮。

+ 專案檔：

    + suffix：`.kmol` (`xml` format)
    + 只記錄樹狀結構、腳本與檔案相對位置，不考慮儲存檔案內容。
    + 樹狀結構不支援巢狀檔案引用。

+ 介面：以目前 `.leo` 設定內的為主。

**Comment by mdecourse** [comment]
Kmol Editor 可以作為利用 Eric6 IDE 建立機械設計專用編輯器的範例, 先建立一個 Makefile, 可以在 MSYS2 模式下, 以 mingw32-make 建立 .exe 執行檔案. 然後再仔細註解程式碼, 讓初學者更容易學習.

Leo Editor 引用 PyQt5 與 PyQt4 的架構非常值得學習, 主要功能與圖形介面的區隔非常清楚, 每次讀原始碼都能有一定的收穫.

**Comment by KmolYuan** [comment]
新版 PyQt 模組已更動：<http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html>

現在必須這樣載入 sip：

```python
from PyQt5 import sip
```

或是：

```python
from PyQt5 import QtCore
import sip
```

因此使用 PyInstaller 包裝時必須將單一的 `--hidden-import=PyQt5` 改為：

```makefile
    pyinstaller -F $< -i ./icons/kmol.ico \
--hidden-import=PyQt5 \
--hidden-import=PyQt5.sip \
--hidden-import=PyQt5.QtPrintSupport
```

另外再加上 `-w` 參數關閉 std 視窗。

這部分看未來 PyInstaller 會不會支援自動找尋新的路徑。

**Comment by KmolYuan** [comment]
https://github.com/KmolYuan/kmol-editor/commit/f1da74fc0c571cb89b697203ec21b92bd82dc542
