### ISSUE TITLE
KLL3PP

### ISSUE THREAD

**Issue by mdecourse** [mdecourse/kll3pp#5]
拿到印表機的 Solidworks 零組件檔案後, 可以先以相同尺寸在 https://www.onshape.com/ 開始進行機械零組件的繪圖, 原則上鋁擠型架構將改用 T-slot 30x30, 且 Z 軸螺桿將加大, 設計尺寸可以與學長討論之後決定.

**Comment by 40623128** [comment]
印表機零件:https://drive.google.com/file/d/18_jpcXanZVwuY6QtV4YDL7Q6u_wH3pK7/view?usp=sharing

**Comment by 40623128** [comment]
先建立新的文件，把下方Assembly 1改名為.zip檔名，再點選左下角+號匯入檔案，但匯入後會顯示轉譯失敗。

**Comment by mdecourse** [comment]
根據 https://cad.onshape.com/help/Content/uploadfiles.htm 說明, 轉組立與零件檔案流程如下:

# SolidWorks assemblies

Onshape needs all of the parts and subassembly files alongside the top level .sldasm file to successfully import a SolidWorks assembly. 

Follow these steps to import a SolidWorks assembly:

  * Use the Pack & Go tool in SolidWorks to create a .zip file of your top-level assembly.
  * Include all parts and subassemblies.
  * Flatten the file structure so there are no folders in the .zip file.
  *  Ensure the top-level assembly and the .zip file have the same name.
  *  Import the entire .zip file into Onshape.

Additionally, Onshape and SolidWorks both run on the Parasolid modeling kernel and exporting a SolidWorks assembly as a Parasolid (.x_t) file is another way to import into Onshape.

# SolidWorks parts

There are no special workflows required to import a SolidWorks part file (.sldprt) into Onshape. Simply select the part file when prompted by the Onshape import dialog. That said, exporting a SolidWorks part as a Parasolid (.x_t) file is another way to import it into Onshape.

**Comment by mdecourse** [comment]
今年開始的服務:

https://nfucc.nfu.edu.tw/zh/download/download-service/2016-05-30-02-17-09

畢業生可以永久使用的套件: Windows 8.1、Windows 10、Office 2013、Office 2016、Office 2011 for Mac、Office 2016 for Mac
